---
apiVersion: groupsnapshot.storage.k8s.io/v1beta2
kind: VolumeGroupSnapshot
metadata:
  name: new-groupsnapshot-demo
spec:
  source:
    selector:
      matchLabels:
        app.kubernetes.io/name: postgresql
  volumeGroupSnapshotClassName: csi-hostpath-groupsnapclass
