apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    createdAt: "2025-05-28T13:05:38Z"
    olm.skipRange: ""
    operators.operatorframework.io/builder: operator-sdk-v1.34.1
    operators.operatorframework.io/operator-type: non-standalone
    operators.operatorframework.io/project_layout: unknown
  name: odf-snapshot-controller.v4.20.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: VolumeGroupSnapshotClass
      name: volumegroupsnapshotclasses.groupsnapshot.storage.openshift.io
      version: v1beta1
    - kind: VolumeGroupSnapshotContent
      name: volumegroupsnapshotcontents.groupsnapshot.storage.openshift.io
      version: v1beta1
    - kind: VolumeGroupSnapshot
      name: volumegroupsnapshots.groupsnapshot.storage.openshift.io
      version: v1beta1
  description: Snapshot Controller provides the snapshot controller for managing volume
    group snapshots
  displayName: Snapshot Controller
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - persistentvolumes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - get
          - list
          - watch
          - update
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - list
          - watch
          - create
          - update
          - patch
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotcontents
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
          - patch
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshotcontents/status
          verbs:
          - patch
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - patch
          - delete
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots/status
          verbs:
          - update
          - patch
        - apiGroups:
          - groupsnapshot.storage.openshift.io
          resources:
          - volumegroupsnapshotclasses
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - groupsnapshot.storage.openshift.io
          resources:
          - volumegroupsnapshotcontents
          verbs:
          - create
          - get
          - list
          - watch
          - update
          - delete
          - patch
        - apiGroups:
          - groupsnapshot.storage.openshift.io
          resources:
          - volumegroupsnapshotcontents/status
          verbs:
          - patch
        - apiGroups:
          - groupsnapshot.storage.openshift.io
          resources:
          - volumegroupsnapshots
          verbs:
          - get
          - list
          - watch
          - update
          - patch
        - apiGroups:
          - groupsnapshot.storage.openshift.io
          resources:
          - volumegroupsnapshots/status
          verbs:
          - update
          - patch
        serviceAccountName: odf-snapshot-controller
      deployments:
      - name: odf-snapshot-controller
        spec:
          minReadySeconds: 35
          replicas: 2
          selector:
            matchLabels:
              app.kubernetes.io/name: odf-snapshot-controller
          strategy:
            rollingUpdate:
              maxSurge: 0
              maxUnavailable: 1
            type: RollingUpdate
          template:
            metadata:
              labels:
                app.kubernetes.io/name: odf-snapshot-controller
            spec:
              containers:
              - args:
                - --v=5
                - --leader-election=true
                - --feature-gates=CSIVolumeGroupSnapshot=true
                image: quay.io/ocs-dev/snapshot-controller:latest
                imagePullPolicy: IfNotPresent
                name: odf-snapshot-controller
                resources: {}
              serviceAccountName: odf-snapshot-controller
      permissions:
      - rules:
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - watch
          - list
          - delete
          - update
          - create
        serviceAccountName: odf-snapshot-controller
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - csi
  - odf-snapshot-controller
  links:
  - name: Snapshot Controller
    url: https://github.com/red-hat-storage/external-snapshotter
  maturity: GA
  provider:
    name: Red Hat Storage
    url: https://github.com/red-hat-storage
  version: 4.20.0
