---
apiVersion: groupsnapshot.storage.k8s.io/v1beta2
kind: VolumeGroupSnapshotContent
metadata:
  name: new-groupsnapshotcontent-demo
spec:
  volumeGroupSnapshotRef:
    name: new-groupsnapshot-demo
    namespace: default
  driver: hostpath.csi.k8s.io
  source:
    volumeHandles:
    - handles
  deletionPolicy: Retain
